import dedent from 'dedent';

const START_MARKER = '<!-- bolt:start -->';
const END_MARKER = '<!-- bolt:end -->';
const HEADER = dedent`
    <!--
    Generated by agent-bolt. Do not edit this block manually.
    Run \`agent-bolt sync\` to update it.
    -->
  `;

export function buildManagedBlockContent(fragments: string[]): string {
  const trimmed = fragments.map((fragment) => fragment.replace(/\s+$/, ''));
  const body = trimmed.length > 0 ? `\n${trimmed.join('\n\n\n')}\n` : '';
  return body;
}

export function buildManagedBlock(content: string): string {
  return `${START_MARKER}\n${HEADER}\n${content}\n${END_MARKER}`;
}

function assertValidMarkers(content: string): void {
  const startMarkerCount = content.split(START_MARKER).length - 1;
  const endMarkerCount = content.split(END_MARKER).length - 1;

  if (startMarkerCount === 0 && endMarkerCount === 0) {
    throw new Error(
      `No bolt managed block markers found. Add the markers below where you want the block, then run \`agent-bolt sync\` again.\n\n${START_MARKER}\n${END_MARKER}`,
    );
  }

  if (startMarkerCount !== 1 || endMarkerCount !== 1) {
    throw new Error(
      `bolt managed markers are unbalanced or duplicated (${startMarkerCount} start, ${endMarkerCount} end). Each must appear exactly once.`,
    );
  }

  if (content.indexOf(START_MARKER) > content.indexOf(END_MARKER)) {
    throw new Error('bolt end marker appears before the start marker. Check their order.');
  }
}

export function replaceManagedBlock(content: string, newBlockContent: string): string {
  assertValidMarkers(content);

  const startMarkerIndex = content.indexOf(START_MARKER);
  const endMarkerIndex = content.indexOf(END_MARKER);

  const beforeBlockContent = content.substring(0, startMarkerIndex);
  const managedBlock = buildManagedBlock(newBlockContent);
  const afterBlockContent = content.substring(endMarkerIndex + END_MARKER.length);

  return beforeBlockContent + managedBlock + afterBlockContent;
}
